version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.21.0
    - 4.22.0
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.1.2
  - dependency-name: styled-components
    versions:
    - 5.2.3
